### ISSUE TITLE
Add a logger to the bot 

### ISSUE THREAD

**Issue by Nothooon** [Nothooon/Brott#3]
Add a logger to the different files rather than using print(). 
Can be done with the `logging` library

**Comment by Nothooon** [comment]
@Loloweb pk y'a deux branches de liées ?

**Comment by Loloweb** [comment]
feature/logs c'est une ébauche basé sur ce que la doc de discord.py proposait, ce qui pour moi est trop compliqué pour pas grand chose au final alors j'ai fait une autre branche sur laquelle j'ai fait ma merde. Tu peut effacer feature/logger.

**Comment by Nothooon** [comment]
ça roule bb, j'vais update le readme avec une petite nomenclature pour nos branches futures, comme ça on sera bien 👌
